### ISSUE TITLE
reflect deprecation in the Dataclasses 

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#514] opened 2021-12-13 21:28 UTC
`SlotDefinition`'s attribute [`owner`](https://linkml.io/linkml-model/docs/owner/) is deprecated within the model. I don't think that's reflected anywhere in the [Dataclass](https://github.com/linkml/linkml-model/blob/ec4bee7c691e2ba5e1b276a95139d1fc77445c38/linkml_model/meta.py#L1069), so I don't get any hint about it in my IDE (PyCharm)

It looks like it is possible to decorate a method as deprecated: https://python-deprecated.readthedocs.io/en/latest/tutorial.html#deprecated-method

**Comment by cmungall** [comment] 2021-12-18 02:18
Dupe with #484?

**Comment by sujaypatil96** [comment] 2022-12-19 23:51
Closing this issue as dupe of #484

**Closed by sujaypatil96** 2022-12-19 23:51 UTC
Labels: enhancement, generator-dataclasses
