### ISSUE TITLE
gen-java creates NO output in the MIxS repository

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#660] opened 2022-03-22 18:40 UTC
MIxS = https://github.com/GenomicsStandardsConsortium/mixs

will provide test case later

**Comment by turbomam** [comment] 2022-03-22 18:40
did try with `--mergeimports`. no help.

**Comment by turbomam** [comment] 2022-03-22 18:42
see also https://github.com/GenomicsStandardsConsortium/mixs/issues/361

**Comment by cmungall** [comment] 2022-07-08 00:12
@sujaypatil96 can you confirm is this still an issue?

**Comment by sujaypatil96** [comment] 2022-12-09 22:58
Check if dupe of #969

**Comment by sierra-moxon** [comment] 2022-12-22 19:24
closing as dupe of #969

**Closed by sierra-moxon** 2022-12-22 19:24 UTC
Labels: generator-misc, backlog
