### ISSUE TITLE
In some cases generation of post_init inlining method prematurely makes a key from some slots

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#463] opened 2021-11-11 14:38 UTC
__UPDATE from CJM__ I created a minimal example, scroll down to https://github.com/linkml/linkml/issues/463#issuecomment-977487300

I don't know if this is a LinkML error or something specific to the CRDC-H model, so I am [cross posting](https://github.com/cancerDHC/ccdhmodel/issues/154) from the repo where the CRDC-H model lives. Note the worked example lives in yet another repo!

TL;DR: I created a YAML datafile by using the CRDC-H Python data classes. When I try to load that (or use linkml-convert), I get the unhashable type: 'CodeableConcept' error

----

including the care crossposted link for link discovery: https://github.com/cancerDHC/ccdhmodel/issues/154

**Comment by gaurav** [comment] 2021-11-19 21:54
- Example file that (correctly) generates a data file: https://github.com/cancerDHC/example-data/blob/061556713077371d25b8b252e142dc08c03ae7a9/gen_diag_with_stage_obs_set.py
  - I'm not sure which version of `crdch_model` Mark was using, but I think you can replicate the error with https://pypi.org/project/crdch-model/1.1.5/
- Example data file that causes an error when reloading it using the YAML loader: https://github.com/cancerDHC/example-data/blob/061556713077371d25b8b252e142dc08c03ae7a9/gen_diag_with_stage_obs_set.yaml

Is there somewhere in the linkml or linkml-runtime repos where something like this could be written up as a test case?

**Comment by cmungall** [comment] 2021-11-24 00:37
ideally this could be distilled into a smaller test case. I'm having a hard time figuring out how to make this actionable. I'm also having a hard time finding the relevant schema on github since it doesn't seem to be tagged with 1.1.5... and it's a large schema

**Comment by cmungall** [comment] 2021-11-24 01:02
OK, I made a more minimal test file:

```yaml
stage:
- method_type: []
  observations:
  - observation_type:
      coding:
      - code: C25605
        system: http://ncithesaurus.nci.nih.gov/
        label: Overall
    value_codeable_concept:
      coding:
      - code: C96258
        system: http://ncithesaurus.nci.nih.gov/
        label: FIGO Stage IIIC
```

script that tests this:

```python
from linkml_runtime.loaders import yaml_loader
from crdch_model import Diagnosis
yaml_loader.load('test.yaml', target_class=Diagnosis)
```


I can replicate the error this way (but still ideally we would have a minimal reproducible test)

I think this is telling:

```python
~/repos/ccdh-test/venv/lib/python3.9/site-packages/crdch_model.py in __post_init__(self, *_, **kwargs)
    441             self.performed_by = Organization(**as_dict(self.performed_by))
    442 
--> 443         self._normalize_inlined_as_list(slot_name="observations", slot_type=CancerStageObservation, key_name="observation_type", keyed=False)
    444 
    445         super().__post_init__(**kwargs)
````

It is wanting to use `observation_type` as the key. I don't have the schema handy but I doubt this is intended

here is the generator code:

https://github.com/linkml/linkml/blob/684f04526a00cb8d2682eebae132eba1af47abef/linkml/generators/pythongen.py#L634-L658

@hsolbrig is this correct? The logic here of using the first required field seems suspect

**Comment by cmungall** [comment] 2021-11-24 03:52
OK, I recreated this with a minimal example, see #488 

I was curious why we haven't seen this before, but it seems the following conditions must be met:

 1. there is a container object with a list of contained objects
 2. the contained objects lack an identifier
 3. the contained objects are inlined as a list (which follows from 2)
 4. the contained object has a required field
 5. the first required field is a nested object which itself lacks an identifier

Conditions 1-4 yield a post_init like:

```python
self._normalize_inlined_as_list(slot_name="contains", slot_type=Contained, key_name="type", keyed=False)
```

This is problematic, as the docs for this method say:

```python
def _normalize_inlined(self, slot_name: str, slot_type: Type, key_name: str, keyed: bool, is_list: bool) \
            -> None:
        """
         __post_init__ function for a list of inlined keyed or identified classes.

        The input to this is either a list or dictionary of dictionaries.  In the list case, every key entry
        in the list must be unique.  In the dictionary case, the key may or may not be repeated in the dictionary
        element. The internal storage structure is a dictionary of dictionaries.
        @param slot_name: Name of the slot being normalized
        @param slot_type: Slot range type
        @param key_name: Name of the key or identifier in the range
        @param keyed: True means each identifier must be unique
        @param is_list: True means inlined as list
        """
```

so even though `keyed=False` this attempts to use `type` as a key, even though me as a schema provider have no intention of this being a key.

**Comment by gaurav** [comment] 2021-11-24 04:37
> I'm also having a hard time finding the relevant schema on github since it doesn't seem to be tagged with 1.1.5... and it's a large schema

Sorry about that! We generated a bunch of PyPI releases in figuring out the best way to publish the `crdch_model` package there, so they don't have tags in the repo. I was planning to delete them once we merge PR https://github.com/cancerDHC/ccdhmodel/pull/127, but that's PR is taking a while to get done. I think this bug exists in the last tagged release, v1.1. However, it looks like you managed to make a minimal example that demonstrates this bug -- wow! I'd love to know how you figured out the five conditions needed to replicate this bug.

**Comment by turbomam** [comment] 2021-12-01 16:48
Thanks for the thorough investigation, @cmungall 

Last time we spoke I think you said that you suggested a workaround, but  I don't see it here. I've been experimenting with this (adding `id`s, in the first position, wherever tolerated) but still can't load the `Diagnosis`. I'll write a test for good measure. 

Let me make sure I understand how we're satisfying the failure conditions you described

1. there is a container object with a list of contained objects
    - are those the CancerStageObservations in the CancerStageObservationSet's `observations`?
2. the contained objects lack an identifier
    - [observations can take `id`s](https://cancerdhc.github.io/ccdhmodel/v1.1/observation__id/). I added one and got the same unhasable type error (as opposed to something like an `id` not allowed error). So maybe I need to go back to point one and reevaluate.
3. the contained objects are inlined as a list (which follows from 2)
4. the contained object has a required field
5. the first required field is a nested object which itself lacks an identifier
    - The first field required in a CancerStageObservation is the `observation_type` which is indeed nested and does not take an `id`

**Comment by turbomam** [comment] 2021-12-01 17:42
I guess I should say that `CancerStageObservation`s have an `id` slot, but that may not have the `identifier` slot asserted in the model.

**Comment by turbomam** [comment] 2021-12-01 21:57
I have a test for this now. It hasn't been merged into main yet.

From branch `issue-27-codable-concept-notebooks` in cancerDHC/example-data:

`pipenv run pytest linkml_linkml_issue_463_test.py`

That succeeds in loading a `Coding`, a `CodeableConcept`, and a `CancerStageObservation` (all from the `crdch-model`), but not a `CancerStageObservationSet`, which meets @cmungall's  5 conditions.

I added `id` slots where possible, but the `id`s in this model don't have the `identifier` attribute from the metamodel asserted.

**Comment by cmungall** [comment] 2021-12-18 02:47
We keep forgetting to bring this up on the calls...

**Comment by sierra-moxon** [comment] 2022-10-07 21:46
@turbomam - can we close this as done?

**Comment by sierra-moxon** [comment] 2022-10-28 17:52
closing as done.

**Closed by sierra-moxon** 2022-10-28 17:52 UTC
Labels: bug
