### ISSUE TITLE
personinfo.xlsx contains SQL DDL

### ISSUE THREAD

**Issue by joshmoore** [linkml/linkml#985] opened 2022-09-28 10:22 UTC
**Describe the bug**

#608 updated the personinfo schema derived artifacts, but apparently the `CREATE TABLE` commands were stored in the personinfo.xlsx rather than the spreadsheet itself:

```
(linkml) /opt/linkml/examples/PersonSchema/personinfo $diff sqlschema/personinfo.sql excel/personinfo.xlsx
(linkml) /opt/linkml/examples/PersonSchema/personinfo $
```

**Comment by sierra-moxon** [comment] 2022-10-03 20:12
Closing as duplicate of #978

**Closed by sierra-moxon** 2022-10-03 20:12 UTC
Labels: bug
