### ISSUE TITLE
Prefix with hyphenated name won't validate JSON

### ISSUE THREAD

**Issue by galund** [linkml/linkml#807] opened 2022-05-31 10:21 UTC
**Describe the bug**
(This bug is similar but not the same as <https://github.com/linkml/linkml/issues/757>.)

A prefix with a hyphenated name causes a `NameError` when compiling to Python in order to validate some JSON.

**To Reproduce**
1. Create a very basic schema with a hyphenated prefix, such as:

```
id: https://example.com/test
name: test-schema
prefixes:
  linkml: https://w3id.org/linkml/
  some-prefix: https://example.com/test1-prefix-name
imports:
  - linkml:types
default_prefix: some-prefix
classes:
  TestClass:
    attributes:
      testProperty:
```

2. Attempt to validate from JSON against that schema eg by running `linkml-validate -s linkml-schemas/basic.yml examples/test.json`

**Expected behavior**
Validation should proceed as if `some-prefix` in the example above were replaced with `someprefix`.

**Actual behavior**
```
  File "[...]/lib/python3.10/site-packages/linkml_runtime/utils/compile_python.py", line 47, in compile_python
    exec(spec, module.__dict__)
  File "test", line 36, in <module>
NameError: name 'SOME' is not defined
```

**Additional context**

**Comment by cmungall** [comment] 2022-05-31 18:16
Thanks for the report!

As an interim measure until we resolve #757 we will implement an option in linkml-validate to bypass instantiating python objects, and pass the dictionary directly to validation

This will be useful anyway, because the python instantiation automatically repairs certain kinds of structural issues - for example if you pass a single value to a multivalued field, it will fix this. This can be handy, but this is not always desirable

**Comment by sierra-moxon** [comment] 2022-09-30 18:26
@ialarmedalien Keeping this ticket open as a stand-in for #897

**Comment by sujaypatil96** [comment] 2022-12-09 22:52
Dupe of #1157

**Comment by sierra-moxon** [comment] 2024-03-29 21:54
ran again, fixed.

**Closed by sierra-moxon** 2024-03-29 21:54 UTC
Labels: bug, linkml-validate, prefixes
