### ISSUE TITLE
`Slot: types` page broken

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#1076] opened 2022-08-26 20:28 UTC
The `Slot: types` page which can be found here: https://linkml.io/linkml-model/docs/types/ is broken.

And the reason for that is because when the `gh-pages` branch is created, you'll see a `types` folder in there with multiple subfolders within it, which is what is causing the break. This probably has something to do with the way GitHub Pages or Mkdocs handles the deployment.

**Comment by sierra-moxon** [comment] 2022-10-28 17:19
duplicate of #883 I believe.

**Comment by sierra-moxon** [comment] 2023-04-21 21:39
fixed! :)

**Closed by sierra-moxon** 2023-04-21 21:39 UTC
Labels: doc-generator
