### ISSUE TITLE
query about initial generation of online schema definition

### ISSUE THREAD

**Issue by druimalban** [linkml/linkml#2118] opened 2024-03-12 12:59 UTC
I have been developing my own data model, and I'm having a bit of trouble understanding how the initial online schema is generated.

From the makefile, as far as I understand, you do this:

1. Run linkml `gen-project` on the `meta.yaml`, which in turn depends on all of the other yaml definitions, like `linkml:types`, `linkml:units`;
2. Run linkml `gen-doc` from the project directory, which generates markdown files;
3. Call `mkdocs` on the generated markdown files.

However, the calls in `meta.yaml` are via the imports directive, which, in the default behavior (going by the gen-project help command, I can't see any other behavior), will fetch these from the URL provided.

This suggests to me that, when you were developing LinkML, you bootstrapped the schema somehow, which generated the initial online definition.

I can work around this by generating documentation for each YAML schema (either manually or in a makefile), and putting it on a local web server (some directory like `localhost/schema` or similar). This is OK for one schema, like your schema.org example, but it becomes increasingly difficult, even with a makefile, for 12 or more different 'child' schemata.

What is the process of generating the schema, in absence of an extant online schema? Is there a way to feed it a directory of YAML schemata which will produce something like [`w3id.org/linkml`](https://w3id.org/linkml/)?

**Comment by turbomam** [comment] 2024-05-17 20:35
Or could we even close this as a duplicate of 
- #1965 
?

**Comment by druimalban** [comment] 2024-05-17 21:28
Yea, I think so, I mostly left it open in case there was engagement on this one instead of that second one. Thanks.

**Closed** 2024-05-17 21:51 UTC
