### ISSUE TITLE
Validator is not working as expected when using Container

### ISSUE THREAD

**Issue by sooyounga** [linkml/linkml#1393] opened 2023-04-14 16:50 UTC
**Describe the bug**
I am trying to use a collection of classes in my schema, just like the example of Person --> persons , using container.
However, it seems like there is an issue of not recognizing the original class when using this container for data mapping. 
Here's an example that is reproducible:
`exampleschema.yaml`
```
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  biolink: https://w3id.org/biolink/vocab/
imports:
  - linkml:types
  - https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model
default_range: string

classes:
  Person:
    is_a: named thing
    attributes:
      full_name:
      aliases:
      phone:
      age:
  Container:
    tree_root: true
    attributes:
      persons:
        multivalued: true
        inlined_as_list: true
        range: Person
```
`exampleschemadata.yaml`
```
persons:
  - full_name: Emily Doe
    aliases: Em
    phone: 123-456-7890
    age: 30
  - full_name: John Smith
    aliases: Joe
    phone: 456-789-0123
    age: 31
```
When validating, `linkml-validate exampledata.yaml -s example.yaml` or `linkml-validate exampledata.yaml -s example.yaml -C "Person"`, I get this name error saying Person is not recognized:
```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/linkml/validators/jsonschemavalidator.py", line 118, in cli
    python_module = PythonGenerator(schema).compile_module()
  File "/opt/anaconda3/lib/python3.9/site-packages/linkml/generators/pythongen.py", line 82, in compile_module
    raise e
  File "/opt/anaconda3/lib/python3.9/site-packages/linkml/generators/pythongen.py", line 78, in compile_module
    return compile_python(pycode)
  File "/opt/anaconda3/lib/python3.9/site-packages/linkml_runtime/utils/compile_python.py", line 47, in compile_python
    exec(spec, module.__dict__)
  File "test", line 1298, in <module>
  File "test", line 1306, in Container
NameError: name 'Person' is not defined
```

**Additional context**
I am trying to use this for my own schema where I am importing an existing model from biolink and build a container on top of that

**Comment by satra** [comment] 2023-04-14 21:16
the key to this issue is the `is_a` relationship introduced in the modification of the class. the original example without `is_a` works fine.

**Comment by cmungall** [comment] 2023-04-20 15:01
Apologies for the delay. I can confirm I can replicate. This is unusual, it appears to be something in the import. If we don't get a quick fix soon I will give you some workarounds.

**Comment by adhollander** [comment] 2023-08-16 22:58
I have run into a similar issue with validating data that is in a container that is using an `is_a` relationship. My schema is borrowing considerably from biolink, in particular using its association model. In it, I have a PersonOrganizationAssociation that `is_a` AgentToAgentAssociation that `is_a` Association.  My container structure in LinkML looks like the following:

```
  associations:
    description: >-
      A multivalued list of all the associations in the system. 
    slot_uri: fsls:associations
    multivalued: true
    inlined_as_list: true
    range: Association # it gives errors if I leave this in, can't find the name Association. Why?
    #range: PersonOrganizationAssociation # it works if I use this as a range...

```

If I specify the range as being PersonOrganizationAssociation, I don't get an error, only if I use Association as the range here.

The last portion of the error message I get is as follows:  

```
  File "/run/media/adh/Elements/WorkScratch/PPODvenv/lib/python3.11/site-packages/linkml/validators/jsonschemavalidator.py", line 159, in cli
    python_module = PythonGenerator(schema).compile_module()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/adh/Elements/WorkScratch/PPODvenv/lib/python3.11/site-packages/linkml/generators/pythongen.py", line 81, in compile_module
    raise e
  File "/run/media/adh/Elements/WorkScratch/PPODvenv/lib/python3.11/site-packages/linkml/generators/pythongen.py", line 77, in compile_module
    return compile_python(pycode)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/adh/Elements/WorkScratch/PPODvenv/lib/python3.11/site-packages/linkml_runtime/utils/compile_python.py", line 50, in compile_python
    exec(spec, module.__dict__)
  File "test", line 215, in <module>
  File "test", line 227, in Container
NameError: name 'Association' is not defined. Did you mean: 'AssociationNid'?
```

I have run this as 

`linkml-validate -f ttl -s PPOD_Core-0.0.4.yaml PPOD_Core_test1.ttl`

Gists for the files in this test are 

- PPOD_Core-0.0.4.yaml https://gist.github.com/adhollander/71d7f4500bbfafdd0cf0eaa5ce74a22c
- PPOD_Core_test1.ttl https://gist.github.com/adhollander/ecd7ff80dbc58c749959b517d18891d1
- PPOD_Core_testerrors.txt https://gist.github.com/adhollander/28dea31bbbed3aa859439c4ef007a061 (the full error message)

Given the NameError message, this issue is also suggestive of the forward referencing problem in https://github.com/linkml/linkml/issues/1168, but I am unable to find a way to reorder the schema as a workaround.

Are there workarounds for my validation issue?

**Comment by pkalita-lbl** [comment] 2023-11-10 22:46
Closing this because the original reproduction steps now work as expected. 

Using the given `exampleschema.yaml` and `exampleschemadata.yaml` files, the command `linkml-validate exampledata.yaml -s example.yaml` does not raise any exceptions. It does report the following validation failures, as expected:

```
[ERROR] [exampleschemadata.yaml/0] 30 is not of type 'string' in /persons/0/age
[ERROR] [exampleschemadata.yaml/0] 'id' is a required property in /persons/0
[ERROR] [exampleschemadata.yaml/0] 'category' is a required property in /persons/0
[ERROR] [exampleschemadata.yaml/0] 31 is not of type 'string' in /persons/1/age
[ERROR] [exampleschemadata.yaml/0] 'id' is a required property in /persons/1
[ERROR] [exampleschemadata.yaml/0] 'category' is a required property in /persons/1
```

**Closed by pkalita-lbl** 2023-11-10 22:46 UTC
Labels: bug, linkml-validate, community-generated
