### ISSUE TITLE
schemaloader accepts formally incorrect schemas - Add optional jsonschema validation to warn modelers

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#567] opened 2022-01-19 00:39 UTC
Continued from https://github.com/microbiomedata/nmdc-schema/pull/239#discussion_r785167685

The schemaloader allows:

 - descriptions to be specified as singleton lists in yaml (even though it is formally singlevalued)
 - comments to be specified as non-list strings, with autoconversion to lists

This is the result of the current post_init design which intentionally performs repairs

Arguably this is handy - the be liberal in what you accept and conservative in what you produce maxim

however, it's potentially confusing and modelers should at least be made aware this is happening

I recommend an optional step in schemaloader that passes through the jsonschemavalidor, default behavior is to warn, but with a strict mode that will fail

**Comment by sujaypatil96** [comment] 2022-12-19 23:43
@cmungall: @sierra-moxon and I were reviewing our understanding of this issue.

Is the expectation that the JSON Schema generated from the LinkML YAML is validated by a JSON Schema Validator like https://github.com/java-json-tools/json-schema-validator?

Can this issue be closed as a dupe of https://github.com/linkml/linkml/issues/1148?

**Comment by cmungall** [comment] 2022-12-20 02:35
It’s a duplicate, yes

**Comment by sierra-moxon** [comment] 2022-12-22 19:25
closing as dupe of https://github.com/linkml/linkml/issues/1148

**Closed by sierra-moxon** 2022-12-22 19:25 UTC
Labels: Low severity, linkml-validate, backlog
