### ISSUE TITLE
import model: target class not specified and could not be inferred

### ISSUE THREAD

**Issue by noelmcloughlin** [linkml/linkml#494] opened 2021-11-30 11:03 UTC
**Describe the bug**
A complete LinkML model could be generated by converging multiple fragments using `import`, since linkml model  fragments may be supplied by different providers/vendors.  However I cannot get import working if model-to-be-imported includes a class.  There seems to be some issue merging classes during validate.

**To Reproduce**
1. Create `slot-usage-example.yaml` and `data.yaml` as documented at https://linkml.io/linkml/intro/tutorial07.html#customizing-slots-in-the-context-of-classes-slot-usage
2. Edit `slot-usage-example.yaml` and add local import:
```
imports:
  - linkml:types        # default
  - testme                # local file
```
3. Create `testme.yaml` with valid content and at least one `classes` defintion:
```
id: file://testmodel
classes:
  annotation:
    description: dummy
    abstract: true
```
4. Run validate `linkml-validate data.yaml -s slot-usage-example.yaml`  to see Error

```
  File "/home/noelmcloughlin/git/hub/linkml-tutorial/venv/lib/python3.8/site-packages/linkml/validators/jsonschemavalidator.py", line 82, in cli
    raise Exception(f'target class not specified and could not be inferred')
Exception: target class not specified and could not be inferred
```

**Expected behavior**
I should be able to import other linkml models which include `classes`.

**Comment by cmungall** [comment] 2021-12-18 02:16
apologies for not getting to this - @sujaypatil96 could you make a test case for this and investigate

@noelmcloughlin - a possible short term workaround is to explicitly pass `--target-class Container` *or* set `tree_root: true` in the `Container` class. If you don't pass this it will try and infer the class which the data object instantiates. It's possible the additional class or import is confusing this inference somehow.

**Comment by noelmcloughlin** [comment] 2021-12-20 17:55
Thanks - I will revisit this when I got a chance. I believe I got this working via `tree_root: true` but I need to revisit.

**Comment by sujaypatil96** [comment] 2022-01-04 04:25
@cmungall: I did some digging into this and as you suspected there's something going wrong in the jsonschemavalidator. It doesn't seem to be inferring the target_class correctly when it isn't specified. It's returning `None` after executing the first `if target_class is None` checker [block](https://github.com/linkml/linkml/blob/main/linkml/validators/jsonschemavalidator.py#L79-L80).

I logged the output of `candidates` from the `infer_root_class` method on this [line](https://github.com/linkml/linkml/blob/a335227b05b0290c21ebae50bb99e16eca57c8eb/linkml/utils/datautils.py#L91), and it looked like this:

```
['Container', 'annotation']
```

Similarly, adding another class to `testme.yaml`, say, `role` or something will add the same class to the above list.

I think the fix for this issue is by modifying the `infer_root_class()` method on [L#91](https://github.com/linkml/linkml/blob/a335227b05b0290c21ebae50bb99e16eca57c8eb/linkml/utils/datautils.py#L91) and check for `if len(candidates) >= 1` rather than just `if len(candidates) == 1`. Do you think this is a reasonable fix?

**Comment by cmungall** [comment] 2022-01-04 23:18
Thanks @sujaypatil96!

I might formulate this a little differently. I don't think it's a problem with JsonSchemaDataValidator - the job of this class is to validate a LinkML object (ie instance of YAMLRoot). A target class can always be deterministically determined for a LinkML object by using the python `type(...)` method (which is in fact what it does).

The problem is actually upstream, we need to first take the users' yaml file and turn it into a LinkML object (using yaml_loader... the same applies for json). This step requires a target class, and this is where the heuristic infer_root_class will be used if the user doesn't specify one, and one isn't explicitly annotated in the schema.

I think in fact we should keep the test for `len(candidates) == 1`. We simply need to make the error reporting easier. If an unambiguous root/container cannot be inferred, we just say:

 - "Multiple potential target classes found: `['Container', 'annotation']`. Please specify a target class using `--target-class` or by adding a `tree_root: true` to the relevant class in the schema

Thanks for adding the test. I think the behavior should be to *expect* an exception if there is no explicit or inferrable unambiguous target class.

Having said all that, I think the infer_root_class method can be improved. The dummy class should be ruled out from being a candidate on two grounds:

 - it is declared abstract
 - it has no multivalued slots that take an object as range

**Comment by sujaypatil96** [comment] 2022-01-05 02:33
Thank you @cmungall. I had created an issue on the linkml-runtime repo, [issue #102](https://github.com/linkml/linkml-runtime/issues/102) which asks the above question, if `YAMLLoader.load()` should support `None` type for `target_class` and I think the answer you're saying is no, it shouldn't.

I've made changes on PR #550 which throws a `RuntimeError` if an unambiguous root cannot be inferred. Corresponding update to the unit test has also been made.

**Closed** 2022-01-05 22:40 UTC
Labels: bug
