### ISSUE TITLE
owl-gen: description from yaml schema should generate rdfs:comments in owl

### ISSUE THREAD

**Issue by smrgeoinfo** [linkml/linkml#511] opened 2021-12-10 22:19 UTC
The description documentation from the yaml schema doesn't get translated into the owl outpu. I would expect the yaml description content to become rdfs:comments on the classes and properties in owl

Running 1.1.13, Windows 10, CLI, generating OWL, format ttl 
command:
gen-owl -o isamples0.3owl.ttl -f ttl iSamplesSchemaBasic0.3.yml
[yaml file](https://github.com/isamplesorg/metadata/blob/main/iSamplesSchemaBasic0.3.yml)

e.g.
```
slots:
    id:
        identifier: true
        range: string
        description: identifier for the JSON object. JSON-LD context should map this to @id
```
would  map to 
```
isam:id rdf:type owl:DatatypeProperty ;
        rdfs:range xsd:string ;
        rdfs:comment "identifier for the JSON object. JSON-LD context should map this to @id" .
```
(see #510 on the mapping of the literal range)

**Comment by cmungall** [comment] 2021-12-11 02:54
Hi @smrgeoinfo 

In the linkml metamodel, the description slot has the slot_uri of skos:definition

```yaml
  description:
    domain: element
    description: a description of the element's purpose and use
    slot_uri: skos:definition
    in_subset:
      - owl
```

This is not very apparent in the online docs https://w3id.org/linkml/description -- we are working on improving the markdowngenerator

So in fact, your yaml translates to a skos:definition triple as intended

```turtle
isam:id a owl:ObjectProperty,
        linkml:SlotDefinition ;
    rdfs:label "id" ;
    rdfs:range isam:String ;
    skos:definition "identifier for the JSON object. JSON-LD context should map this to @id" .
```

I would recommend using comment for rdfs:comments

We are open to suggestion for alternate mappings for metamodel properties though - perhaps we should have separate tickets for these? I'll close this for now as I think this is working as intended, but feel free to reopen or open a new issue if this still isn't working to your satisfaction!

**Closed by cmungall** 2021-12-11 02:54 UTC

**Comment by smrgeoinfo** [comment] 2021-12-12 16:33
Interesting. Going back to the raw LinkML output before I edited, the skos:defintions are there. After editing using Protege, they disappeared in my final hand-crafted document. I'm not sure what happened.

**Comment by cmungall** [comment] 2021-12-16 00:01
odd.. but note that the OWL transform should turn slots into Data or Object properties, not Annotation properties. This is maybe odd for an OBO modeling viewpoint, where things like comments and descriptions are metadata outside the model, and are relatively unconstrained. We could have a mechanism to allow some slots to be modeled as APs. But note that you lose the ability at the OWL level to then apply things like cardinality constraints.

**Comment by noelmcloughlin** [comment] 2023-02-20 00:34
I found this thread and now realize there is no mapping to `rdfs:comment`.

**Comment by noelmcloughlin** [comment] 2023-02-20 17:03
Actually this works `--metadata-profile rdfs` and generates `rdfs:comment` instead of `skos:definition`
