### ISSUE TITLE
cleanup "Output mismatch" test output

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#587] opened 2022-01-28 21:48 UTC
from linkml call

https://github.com/linkml/linkml/runs/4971195202?check_suite_focus=true#step:6:2309

![image](https://user-images.githubusercontent.com/50745/151626245-29b35444-5daf-48c2-ba0d-443d93b44243.png)

**Comment by cmungall** [comment] 2022-02-08 19:18
See also https://github.com/linkml/linkml-runtime/blob/document_tests/tests/Testing.md

**Comment by cmungall** [comment] 2022-02-10 00:10
@hsolbrig has a plan for fixing this

**Comment by sierra-moxon** [comment] 2022-11-18 22:51
We want to put integration tests into a separate project so that a change that affects all the emitted JSON (for example), the output mismatch warnings get overwhelming (and the outputted files get pushed into your PR).  So the idea here is to move this output somewhere else.

**Comment by sierra-moxon** [comment] 2022-12-02 21:10
#602 is another instance of this ticket.

**Comment by sierra-moxon** [comment] 2022-12-02 21:16
#880 is another instance of this ticket.

**Comment by sujaypatil96** [comment] 2022-12-09 22:59
Will be resolved as part of testing framework refactor from @hsolbrig

**Comment by sujaypatil96** [comment] 2022-12-09 22:59
CC: @sujaypatil96

**Comment by pkalita-lbl** [comment] 2024-01-05 22:56
Duplicate of #335

**Closed by pkalita-lbl** 2024-01-05 22:56 UTC
Labels: testing
