### ISSUE TITLE
Running the test suite should not change any version-controlled files

### ISSUE THREAD

**Issue by dalito** [linkml/linkml#880] opened 2022-07-22 08:43 UTC
Running the test suite changes many files which messes up `git status` (2687 modified files). While shell scripts are available for resetting the repo back to original state or for ignoring the changes it is somewhat inconvenient especially on Windows where the unix shell tools are typically not available. Moreover, linkml is deviating from most other Python projects in this regard. Normally running the test suite does not mess up your git repository.

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

**Comment by cmungall** [comment] 2022-07-22 21:53
I would love to get this sorted out. Some related issues here: https://github.com/orgs/linkml/projects/11

**Comment by sierra-moxon** [comment] 2022-12-02 21:16
duplicate of #587

**Closed by sierra-moxon** 2022-12-02 21:16 UTC
Labels: testing
