### ISSUE TITLE
rdflib_shim dependency causing an error

### ISSUE THREAD

**Issue by hrshdhgd** [linkml/linkml#529] opened 2021-12-21 00:07 UTC
**Describe the bug**
[SSSOM-PY](https://github.com/mapping-commons/sssom-py) has `linkml-runtime` as a dependency which in turn has `rdflib_shim` as a dependency. Without much change in the code in `sssom-py`, an error started being thrown after the new release 3 days ago. The error is as follows:

```
    def serialize_shim(*args, **kwargs) -> DecodableStr:
>       return DecodableStr(orig_serialize(*args, **kwargs).decode())
E       AttributeError: 'NoneType' object has no attribute 'decode'

.tox/py/lib/python3.9/site-packages/rdflib_shim/__init__.py:30: AttributeError
```

As a band-aid solution , I've pinned linkml-runtime to v1.1.10. The relevant [PR is here](https://github.com/mapping-commons/sssom-py/pull/163).

**Comment by cmungall** [comment] 2021-12-21 23:22
@hrshdhgd did you link to the correct PR?

**Comment by hsolbrig** [comment] 2021-12-21 23:26
Make sure you are using rdflib-shim version 1.0.3

**Comment by cmungall** [comment] 2021-12-21 23:34
good tip

however, developers of libs like sssom-py shouldn't need to worry about pinning dowstream dependencies - they need linkml-runtime to work out the box. Should we pin rdflib-shim in linkml-runtime?

**Comment by cmungall** [comment] 2021-12-21 23:40
@hrshdhgd I am unable to reproduce your issue. I don't see the problematic PR on the list of open PRs in sssom-py

However, I made a PR on sssom-py which uses the latest linkml-runtime (which uses the shim)
https://github.com/mapping-commons/sssom-py/pull/190

This passes the tests, so I'm going to close this until we have a reproducible error

**Closed by cmungall** 2021-12-21 23:40 UTC
Labels: bug
